referee: #radar
  use_image_transmission_link: true
  read:
    - 0x0001 # GameStatus
    - 0x0002 # GameResult
    - 0x0003 # GameRobotHp

    - 0x0101 # EventData
    - 0x0102 # ExtSupplyProjectileAction
    - 0x0104 # RefereeWarning
    - 0x0105 # DartInfo


    - 0x0201 # RobotStatus
    - 0x0207 # ShootData
    - 0x0208 # ProjectileAllowance
    - 0x0209 # Rfid_Status
    - 0x020C # RadarMarkData
    - 0x020E # RadarInfo

    - 0x0301 # RobotInteractionData
    - 0x0302 # CustomRobotData


  write:
    - 0x0301 # RobotInteractionData
    #- 0x0305 # MapRobotData

  ui:
    string:
      manipulator:
        id: 0x010001 # maipulator mode display
        figure_type: string
        layer: 0
        color: white
        width: 2
        size: 25
        length: 11
        start_position: 
        - 100  
        - 850
        context: MANIPULATOR
        frequency: 49

      pitch:
        id: 0x010002 # maipulator mode display
        figure_type: string
        layer: 0
        color: white
        width: 2
        size: 25
        length: 5
        start_position: 
        - 1200 
        - 800
        context: PITCH
        frequency: 5
    
      pump:
        id: 0x010003 # maipulator mode display
        figure_type: string
        layer: 0
        color: white
        width: 2
        size: 25
        length: 4
        start_position: 
        - 1600 
        - 820
        context: PUMP
        frequency: 29

      rod:
        id: 0x010005 # maipulator mode display
        figure_type: string
        layer: 0
        color: white
        width: 2
        size: 25
        length: 3
        start_position: 
        - 1600 
        - 750
        context: ROD
        frequency: 33

      deflection:
        id: 0x010007 # maipulator mode display
        figure_type: string
        layer: 0
        color: white
        width: 2
        size: 25
        length: 3
        start_position: 
        - 1600 
        - 680
        context: DEF
        frequency: 35

      
    graphs:
      pump:
        id: 0x060001 # maipulator mode display
        figure_type: circle
        layer: 0
        color: green
        width: 15
        radius: 20
        center_position: 
        - 1750  
        - 780
        frequency: 51


      deflection:
        id: 0x060003 # maipulator mode display
        figure_type: circle
        layer: 0
        color: orange
        width: 15
        radius: 20
        center_position: 
        - 1750  
        - 680
        frequency: 59


    #   411: # right line
    #     figure_type: line
    #     layer: 0
    #     color: 8
    #     width: 10
    #     start_position: {1360, 0}
    #     end_position: {1160, 450}
    lines:
      line1:
        id: 0x030001 # maipulator mode display
        figure_type: line
        layer: 0
        color: yellow
        width: 1
        start_position: 
        - 900  
        - 250
        end_position: 
        - 870  
        - 0
        frequency: 101
      line2:
        id: 0x030002 # maipulator mode display
        figure_type: line
        layer: 0
        color: yellow
        width: 1
        start_position: 
        - 1125 
        - 250
        end_position: 
        - 1300  
        - 0
        frequency: 105
      line3:
        id: 0x030003 # maipulator mode display
        figure_type: line
        layer: 0
        color: yellow
        width: 1
        start_position: 
        - 880  
        - 800
        end_position: 
        - 880  
        - 400
        frequency: 107
      line4:
        id: 0x030004 # maipulator mode display
        figure_type: line
        layer: 0
        color: yellow
        width: 1
        start_position: 
        - 980
        - 800
        end_position: 
        - 980  
        - 400
        frequency: 109
      line5:
        id: 0x030005 # maipulator mode display
        figure_type: line
        layer: 0
        color: yellow
        width: 1
        start_position: 
        - 1080  
        - 800
        end_position: 
        - 1080  
        - 400
        frequency: 113
      line6:
        id: 0x030006 # maipulator mode display
        figure_type: line
        layer: 0
        color: yellow
        width: 1
        start_position: 
        - 780  
        - 800
        end_position: 
        - 780  
        - 400
        frequency: 117
      line7:
        id: 0x030007 # maipulator mode display
        figure_type: line
        layer: 0
        color: yellow
        width: 1
        start_position: 
        - 1180  
        - 800
        end_position: 
        - 1180  
        - 400
        frequency: 119


